// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rtovcwbyigkkzbxitcuo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ0b3Zjd2J5aWdra3pieGl0Y3VvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzAyOTgxNjgsImV4cCI6MjA4NTg3NDE2OH0.RHX3h3ezSF9cRlMSI5iEoOROXLJ5jo7l0Ao9tjhT-GQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});