// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://esmesnsparlcnxjbihtu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVzbWVzbnNwYXJsY254amJpaHR1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc3OTQyNjQsImV4cCI6MjA3MzM3MDI2NH0.F6MUdU9zokfcNTXXBPQDY3cAyCqqRO5WnaQo01QcVJk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});